### PR TITLE
Don't assume the current readtable is modifiable.

### PR DESCRIPTION
**Pull request by metawilm**
Fixes error when run on Allegro from command line using -e arg.

### CODE REVIEW

**Comment by lisp** [comment]
this is necessary, because the next line modifies the read table state.
that was present in the original. (http://git.b9.com/?p=puri.git;a=blob;f=src.lisp#l1323)
current best practice is to avoid such global read table changes and, in any event, i use a speculative syntax  for iri, which dispatches on the '<' character.
given these, i would be amenable to eliminating the dispatch character modification entirely or otherwise #+'ing it.
thoughts?

**Comment by metawilm** [comment]
I would vote for eliminating entirely, so that the library user can control where and when to enable it.
But it might be friendly to provide a function that sets up the syntax in a given readtable:

```
(defun setup-sharp-u-reader (&optional (readtable *readtable*))
  (set-dispatch-macro-character #\# #\u #'puri::sharp-u readtable))
```

**Comment by lisp** [comment]
go ahead and i will merge it.

**Comment by metawilm** [comment]
OK. This pull request has been superseded by https://github.com/lisp/com.b9.puri.ppcre/pull/2

**Pull request closed without merging**
